//
// Generated file, do not edit! Created by nedtool 5.4 from AirportMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __AIRPORTMESSAGE_M_H
#define __AIRPORTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AirportMessage.msg:21</tt> by nedtool.
 * <pre>
 * message AirportMessage
 * {
 *     double delay;
 * }
 * </pre>
 */
class AirportMessage : public ::omnetpp::cMessage
{
  protected:
    double delay;

  private:
    void copy(const AirportMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AirportMessage&);

  public:
    AirportMessage(const char *name=nullptr, short kind=0);
    AirportMessage(const AirportMessage& other);
    virtual ~AirportMessage();
    AirportMessage& operator=(const AirportMessage& other);
    virtual AirportMessage *dup() const override {return new AirportMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getDelay() const;
    virtual void setDelay(double delay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AirportMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AirportMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __AIRPORTMESSAGE_M_H

