//
// Generated file, do not edit! Created by nedtool 5.4 from passenger.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PASSENGER_M_H
#define __PASSENGER_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>passenger.msg:20</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Passenger
 * {
 *     int someField;
 *     bool isDirty = false;
 * }
 * </pre>
 */
class Passenger : public ::omnetpp::cMessage
{
  protected:
    int someField;
    bool isDirty;

  private:
    void copy(const Passenger& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Passenger&);

  public:
    Passenger(const char *name=nullptr, short kind=0);
    Passenger(const Passenger& other);
    virtual ~Passenger();
    Passenger& operator=(const Passenger& other);
    virtual Passenger *dup() const override {return new Passenger(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField);
    virtual bool getIsDirty() const;
    virtual void setIsDirty(bool isDirty);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Passenger& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Passenger& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PASSENGER_M_H

